### ISSUE TITLE
Secret key derivation

### ISSUE THREAD

**Issue by pbtrung** [vstakhov/hpenc#1]
Hello,

Thank you for this great piece of software. I am actually using it to encrypt `5TB` of movies to store on cloud.
Therefore, could you please shed more lights on the key derivation scheme that `hpenc` is using? Is it "secure" enough compared to, e.g., `scrypt` or `bcrypt`? I would like to ask for your thoughts on `hpenc` implementations.
I am by no means a cryptographer as well as an experienced developer. Just want to know for sure that my encrypted collection would be safe in foreseeable future.

Thanks.

**Comment by vstakhov** [comment]
For `hpenc`, I use the traditional [pbkdf2](http://en.wikipedia.org/wiki/PBKDF2) with the following parameters:
- PRF: HMAC-SHA512
- Salt length: 24 bytes
- Rounds number: 65536

It has almost the same security margin as `bcrypt` and is slightly less complex if attacked by special hardware than `scrypt` (as `scrypt` involves some additional memory being used). Nonetheless, I'm pretty sure that the selected PBKDF is secure enough for the next decade of years. I could change it after [PBKDF security competition](https://password-hashing.net/index.html) would be completed.

**Comment by pbtrung** [comment]
In `HPEncKDF::genKey`, you have used `if (pimpl->password)` before `xchacha(...)`. Does it mean if I use pre-shared key instead of password, `hpenc` will use `xchacha` to derive key rather than PBKDF2. I am a little confused with your previous reply.
Thanks.

**Comment by vstakhov** [comment]
It uses `xchacha` to generate session keys. The pre-shared key is generated from the password using `PBKDF`. So if an attacker knows some plaintext parts he or she can try to brute-force the whole chain starting from some randomly picked password then applying `PBKDF` to generate `xchacha` key and then applying `xchacha` iterations to derive session keys.

**Comment by pbtrung** [comment]
What is the password that you mentioned if I only call `hpenc psk`(no input from me)?

**Comment by vstakhov** [comment]
In case of PSK, it is specified explicitly without any PBKDF step. In case of password, PSK is derived from the password using PBKDF.

**Comment by pbtrung** [comment]
Thanks for clarifying. I will close this.
Keep up this great work!
