### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by pbtrung** [vstakhov/hpenc#4]
Error message:
[ 12%] Building CXX object CMakeFiles/hpenc.dir/src/aead.cc.o
In file included from /usr/include/c++/7.1.1/memory:80:0,
                 from /home/xxxx/hpenc/src/aead.h:26,
                 from /home/xxxx/hpenc/src/aead.cc:29:
/usr/include/c++/7.1.1/bits/unique_ptr.h: In instantiation of ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = evp_cipher_ctx_st]’:
/usr/include/c++/7.1.1/bits/unique_ptr.h:268:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = evp_cipher_ctx_st; _Dp = std::default_delete<evp_cipher_ctx_st>]’
/home/xxxx/hpenc/src/aead.cc:77:19:   required from here
/usr/include/c++/7.1.1/bits/unique_ptr.h:76:22: error: invalid application of ‘sizeof’ to incomplete type ‘evp_cipher_ctx_st’
  static_assert(sizeof(_Tp)>0,
                      ^
make[2]: *** [CMakeFiles/hpenc.dir/build.make:63: CMakeFiles/hpenc.dir/src/aead.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/hpenc.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

ArchLinux: gcc 7.1.1, OpenSSL 1.1.0f (probably because of this).
Thanks.

**Comment by vzhd1701** [comment]
[ 12%] Building CXX object CMakeFiles/hpenc.dir/src/aead.cc.o
In file included from /usr/include/c++/6/memory:81:0,
                 from /root/hpenc/src/aead.h:26,
                 from /root/hpenc/src/aead.cc:29:
/usr/include/c++/6/bits/unique_ptr.h: In instantiation of 'void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = evp_cipher_ctx_st]':
/usr/include/c++/6/bits/unique_ptr.h:239:17:   required from 'std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = evp_cipher_ctx_st; _Dp = std::default_delete<evp_cipher_ctx_st>]'
/root/hpenc/src/aead.cc:77:19:   required from here
/usr/include/c++/6/bits/unique_ptr.h:74:22: error: invalid application of 'sizeof' to incomplete type 'evp_cipher_ctx_st'
  static_assert(sizeof(_Tp)>0,
                      ^
CMakeFiles/hpenc.dir/build.make:62: recipe for target 'CMakeFiles/hpenc.dir/src/aead.cc.o' failed
make[2]: *** [CMakeFiles/hpenc.dir/src/aead.cc.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/hpenc.dir/all' failed
make[1]: *** [CMakeFiles/hpenc.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Getting the same error on Debian Stretch
libssl-dev/stable,stable,now 1.1.0f-3+deb9u2
libsodium-dev/stable,now 1.0.11-2 amd64

I am running
cmake .
make
